FirstWeek/24.03.04.md
README.md

- TIL 리포지토리 세팅
- Github 명령어 정리

240304_25_전성수

---

README.md
git/00_설치.md
git/01_시작.md

240304_22_이필립 TIL

---

README.md

240304_21_이서우 TIL 작성

---

README.md

240304 TIL (26_전수빈)

---

README.md

240304_27_전종현 TIL folk

---

01.Git/01.Git 설치 및 기초.md
README.md

237ff2a73a7fbb05f7f5fbcc41e92cb64482fed7
- chore 오타수정 
9ff228caa3028908d0658a3c6db1f9603d9ec4d4
- 01.Git/01.Git 설치 및 기초.md 파일 수정
658a55efc238bb07cf3a3c148081cf5bb4ce34e2
- 01.Git/01.Git 설치 및 기초.md 작성 및 추가

240305_01_김동혁 TIL

---

2024/03/240305.md

240305_12_성종호

---

dart/01_Created dart.md

240305_34_한정은

---

dart/01. 기본문법.md
git/02. git최초 설정하기.md

- dart. 01.기본문법
- git 02.최초 설정하기

240305_03_김세진

---

2024/03/240306.md

240306_12_성종호

---

Error correction/VSC/console input error.md
OrmCamp/03_일차.md

1. Git 제출가이드
2. 형변환
3. 연산자
4. 함수의 형태
5. 매개변수
6. VSC console 인풋값 인식오류 해결

240306_35_황태욱

---

README.md
기타문법_문자열보간법, 상수타입생략, 증임연산, For문, namedParameter.md
타입을변환하는방법.md

- 기타문법(문자열보간법, 상수타입생략, 증임연산, for문, namedParameter)
- 타입을 변환하는 방법과 안전하게 처리하는 방법

240306_11_서현웅

---

.idea/.gitignore
.idea/TIL.iml
.idea/misc.xml
.idea/modules.xml
.idea/vcs.xml
flutter_A-Z/dart 기본 문법.md

- 다트 기본 문법에 대해 정리합니다.
- 함수 형태, 기본 자료형, 조건문, 반복문, 연산자(산술,증감,비교,논리), 타입검사, 형변환, 매개변수

240306_14_송윤지

---

240307_02_김민규
240307_02_김민규.md

240307_02_김민규

---

Dart/Syntax basics/Operators.md
Dart/Syntax basics/Variables.md

- 'Final and Const' 내용 추가
- 'Operators' 정리

240307_27_전종현

---

Dart/day3.md

240307_16_신승찬 TIL 작성

---

dart/02_class_and_instance.md
dart/03_null_safety.md
git/01_commit_message_convention.md

**git 내용 추가**
- 커밋 메시지 컨벤션
**dart 내용 추가**
- 클래스와 인스턴스
- null-safety

240307_08_박세훈

---

README.md
dart/00_final_vs_const.md
dart/02_class_and_instance.md
dart/03_null_safety.md
dart/04_parameter.md

**dart 내용 추가**
- Parameter, 매개 변수
**README 수정**

240308_08_박세훈

---

Dart/생성자.md
Dart/클래스.md
Error correction/클래스 생성자에 final 상수가 들어가지 않음.md
OrmCamp/05_일차.md

240308_35_황태욱

---

Nullable을 안전하게 다루는 방법.md
README.md
final_상수의_값이_없었던이유.md
late 키워드를 잘 활용하는 방법.md

- Nullable을 안전하게 다루는 방법
- final 상수의 값이 없었던 이유
- late 키워드를 잘 활용하는 방법

240308_11_서현웅

---

ormcamp/24.03.11.md

test code
encapsulation
collection

240311_06_김형민 TIL

---

orm/(0311)encapsulation_n_collection.md

240311_24_장날아

---

dart/03_11_dart.md

캡슐화
● 접근 제한자
● 프로퍼티
컬렉션
● List
● Set
● Map
테스트 코드
● 작성 예제

240311_32_최지원

---

Dart/day5.md

240311_16_신승찬

---

240312_04_김윤아.txt

240312_04_김윤아

---

README.md
dart/06_inheritance.md

**Dart 상속 추가**
- Dart 디렉토리에 06_Inheritance.md 추가

240312_08_박세훈

---

ormcamp/24.03.12.md

240312_06_김형민 TIL

---

Dart/Syntax basics/Comments.md
Dart/Syntax basics/Libraries&imports.md
Dart/Syntax basics/Variables.md
Dart/Types/Built-in types.md
Dart/Types/Records.md
README.md

- Libraries & imports 정리
- Records 정리
- Built-in-types 정리
- 기타 형식 수정

240312_27_전종현

---

dart/03_12_dart.md

240312_32_최지원

---

README.md
dart/07_var_vs_dynamic.md
dart/08_abstract_class_vs_interface.md

**Dart 디렉토리에 추가**
- var vs dynamic
- 추상 클래스와 인터페이스
**README 수정**

240313_08_박세훈

---

dart/09. 추상클래스와 인터페이스.md

- 추상클래스(Abstract class)와 인터페이스(Interface)

240313_03_김세진

---

오름/8일차 (추상화, 인터페이스).md

240313_13_성효정 TIL

---

240313_04_김윤아

240313_04_김윤아

---

dart/09_polymorphism.md

**Dart 다향성 초안 추가**
- 내용 추후 추가 예정

240314_08_박세훈

---

ormcamp/24.03.14.md

240314_06_김형민 TIL

---

오름/9일차 (다형성).md

240314_13_성효정 TIL.md

---

Dart/다형성.md
OrmCamp/2주차/4_일차.md

240314_35_황태욱

---

02.Dart/011 Dart - 다형성.md

다형성 학습
- 02.Dart\011 Dart - 다형성.md 파일 생성 및 작성

240314_01_김동혁 다형성 학습

---

lecture/10일차 정리(Object 관련 정리).md

Create 10일차 정리(Object 관련 정리).md

240315_15_송진섭

---

dart/11. 인스턴스(Instance).md

- 인스턴스의 기본 조작
- object클래스의 3가지 대표 메서드 및 프로퍼티
- toString() , operator ==, hashCode

240315_03_김세진

---

Dart/인스턴스.md
OrmCamp/2주차/5_일차.md

240315_35_황태욱

---

README.md
dart/07_var_dynamic_object.md

**Dart**
- var vs dynamic => var, dynamic, object로 이름 변경 및 내용 수정

240315_08_박세훈

---

Dart/day9.md

240315_16_신승찬

---

dart/09_polymorphism.md
dart/10_generic.md
dart/11_enum.md

- dart 디렉토리에 Generic, enum 추가
- Polymorphism 내용 추가

240318_08_박세훈

---

lecture/11일차 정리(문자열조작,제네릭,열거형).md

Create 11일차 정리(문자열조작,제네릭,열거형).md

240318_15_송진섭

---

orm/(0318)generic, enum, string.md

240318_24_장날아

---

오름/11일차 (제네릭, 문자열).md

240318_13_성효정 TIL

---

ormcamp/24.03.18.md

240318_06_김형민 TIL

---

dart/11_polymorphism.md
dart/12_인스턴스 기본 조작.md
dart/13_generic & enum.md
dart/14_문자열 기본 조작.md

240318_17_신예진

---

Dart/generic.md

generic, enum
- enum 열거형
- String 문자열 처리

240318_18_양혜영

---

Dart/Types/Generics.md

Update. 'Generics' 선언 지점 변성 내용 추가

240318_27_전종현

---

lecture/12일차정리(예외, 파일조작, 데이타형식).md

Create 12일차정리(예외, 파일조작, 데이타형식).md

240319_15_송진섭

---

dart/13_generic & enum.md
dart/14_문자열 기본 조작.md
dart/15_exception.md
dart/16_파일조작.md
dart/17_데이터 형식.md

240319_17_신예진

---

dart/02 문법/17 파일조작.md
dart/02 문법/18 데이터 형식.md
dart/02 문법/18-1 직렬화.md

- 예외의 종류와 에러 상황 별 처리, 예외 처리의 흐름에 대한 정리  [🔗](https://github.com/yujiyeong/TIL/blob/main/dart/02%20%EB%AC%B8%EB%B2%95/16%20%EC%98%88%EC%99%B8%EC%B2%98%EB%A6%AC.md)
- 파일 조작의 기본 순서와 파일을 열고, 읽고, 쓰는 등..의 조작 정리 [🔗](https://github.com/yujiyeong/TIL/blob/main/dart/02%20%EB%AC%B8%EB%B2%95/17%20%ED%8C%8C%EC%9D%BC%EC%A1%B0%EC%9E%91.md)
- 다양한 데이터 형식에 대해 간단하게 정리 [🔗](https://github.com/yujiyeong/TIL/blob/main/dart/02%20%EB%AC%B8%EB%B2%95/18%20%EB%8D%B0%EC%9D%B4%ED%84%B0%20%ED%98%95%EC%8B%9D.md)
- Dart에서의 직렬화 내용 정리 [🔗](https://github.com/yujiyeong/TIL/blob/main/dart/02%20%EB%AC%B8%EB%B2%95/18-1%20%EC%A7%81%EB%A0%AC%ED%99%94.md)    
_(뭔가... 헷갈려서 스스로 정리가 더 필요할 듯 하다...)_
- 간단한 개념만 정리.. 예제 풀이 등이 필요하다. [🔗](https://github.com/yujiyeong/TIL/blob/main/dart/02%20%EB%AC%B8%EB%B2%95/15%20regex.md)
> 제가 18일차 PR을 늦게 …

240319_19_유지영 TIL

---

dart/03_20_dart.md

240320_32_최지원

---

dart/15. 람다식(Lamda)과 함수.md

240320_03_김세진

---

README.md
dart/13_higher_order_function.md
dart/14_async.md

240321_08_박세훈

---

ormcamp/24.03.20.md
ormcamp/24.03.21.md

240321_06_김형민 TIL

---

dart/19_lambda expression & functional programming.md
dart/20_sync & async.md

- sync
- async
- future
- then
- async await
- Future.wait & .delayed & .timeout
- try catch

240321_17_신예진

---

Dart/[Dart] 비동기(Asynchronous) VS 동기(synchronous) 프로그래밍.md

240321_10_변희선

---

Dart/비동기프로그래밍.md

비동기 프로그래밍
- Future
- async - await

240321_18_양혜영

---

lecture/16일차정리(DataSource)

240325_15_송진섭

---

dart/21_datasource.md

- datasource
- http 라이브러리
- 모범답안

240325_17_신예진

---

dart/17. 데이터소스(Data Source).md

- **DataSource**의 개념
- **JSON**의 이해와 사용방법

240325_03_김세진

---

Dart/[Dart] 데이터 변환_JSON통신받아서 변환.md
Dart/[Dart]DataSource .md

240325_10_변희선

---

ormcamp/24.03.25.md

240325_06_김형민 TIL

---

dart/02 문법/18-3 datasource_직렬화.md

- http install 방법과 import하기
- data class 작성
- data source를 사용 가능한 데이터로 변환하기 위한 fromJson, jsonDecode, map과 toList 함수 사용

240325_19_유지영 TIL

---

dart/22_model class & repository.md

- Model 방법
- 모델 클래스 작성 예시 
- Repository 패턴

240326_17_신예진

---

ormcamp/24.03.26.md

240326_06_김형민 TIL

---

dart/15_model.md

240326_08_박세훈

---

dart/18. Model Class, Repository 개념.md

- Model Class의 개념, 책임, 역할 정리
- Repository Pattern의 개념, 책임, 역할 정리

240326_03_김세진

---

Dart/모델클래스_레포지토리.md
Dart/비동기프로그래밍.md

모델클래스와 레포지토리 개념
- 모델클래스 개념
- api와 레포지토리 관계 이해
- 레포지토리 패턴

240326_18_양혜영

---

OrmCamp/4주차/2_일차.md

240326_35_황태욱

---

dart/02 문법/22 repository pattern.md

- repository 선언과 호출 방법, api 등 예시를 작성했습니다.

240326_19_유지영 TIL

---

ormcamp/24.03.27.md

240327_06_김형민 TIL

---

dart/19. Unit Test.md

- Unit Test의 개념
- Unit Test의 목적
- 화이트박스테스트, 블랙박스테스트
- Mock 객체 활용
- Mock 객체 활용 예시

240327_03_김세진

---

dart/24_dto(data transfer object).md

- DTO란?
- DTO vs Model 차이점
- extension을 사용한 Mapper

240328_17_신예진

---

dart/20. DTO, Mapper.md

- DTO의 개념
- DTO의 활용 예시
- DTO를 사용하는 이유
- Mapper의 개념
- Mapper의 활용 예시
- Mapper를 사용하는 이유
- Mapper vs DTO
- 데이터의 흐름

240328_03_김세진

---

README.md
dart/17_dto_and_mapper.md

240328_08_박세훈

---

ormcamp/24.03.28.md

240328_06_김형민

---

02.Dart/025 Dart - DTO,  Mapper.md

DTO, Mapper 학습
chore: 02.Dart\025 Dart - DTO,  Mapper.md 생성 및 작성

240328_01_김동혁 TIL

---

dart/02 문법/25 dto와 model, mapper.md

`dto` `model` `mapper` 에 대해 예시 코드 등과 함께 정리
- repository, api 시 리턴 타입 등이 너무 헷갈린다...
- 쿼리 함수를 사용 할 때 직전 앞의 타입을 확인하는게 아직 어렵다.. 어떤건 되고 어떤건 안되고.. 핸들링을 잘 못하고 있으니 공부하기.. 결론은 공부....
- 어려운 디버깅...

240328_19_유지영 TIL

---

dart/17_ Dart Grammer.md

240328_34_한정은

---

ormcamp/24.03.29.md

240329_06_김형민

---

dart/18_ Dart Grammer.md

240329_34_한정은

---

dart/21. 네트워크 통신.md

- 네트워크 통신의 개념
- JSON의 기본 개념
- HTTP의 개념과 사용 예시
- RESTful API의 개념과 사용 예시

240329_03_김세진

---

Coding/HTTP.md
Dart/Json Serializable.md
OrmCamp/4주차/5_일차.md

240329_35_황태욱

---

dart/02 문법/25-1 jsonSerializable.md

- Live Template 설정 방법 정리
- 실제 사용한 것 정리

240329_19_유지영 TIL

---

practice/00_pixabay_search_images_api.md

240401_08_박세훈

---

lecture/21일차(Result 패턴).md

240401_15_송진섭

---

Dart/Result 패턴.md
OrmCamp/5주차/1_일차.md

240401_35_황태욱

---

ormcamp/24.04.01.md

240401_06_김형민 TIL

---

Dart/[Dart]Result 패턴.md
[API][Postman]사용법.md
[AndroidStudio]Live Template.md
[Dart]@freeze 설치.md

240401_10_변희선

---

dart/19_Dart Grammer.md

예외 처리 기능에 대한 Result class / freezed library / api 활용

240401_34_한정은

---

lecture/22일차(설계 원칙, 디자인 패턴).md

240402_15_송진섭

---

Dart/[Dart] Repository 패턴.md

240402_10_변희선

---

day20.md

240402_16_신승찬

---

orm/(0402)설계원칙, 디자인 패턴.md

240402_24_장날아

---

lecture/23일정리(레이아웃).md

240403_15_송진섭

---

flutter/00_alignment_and_textalign.md

240403_08_박세훈

---

ormcamp/24.04.03.md

240403_06_김형민 TIL

---

flutter/01. Layout.md

- flutter의 레이아웃
- 기본적인 Widget들의 개념과 사용예시

240403_03_김세진

---

240404_Day_24_TIL.md

240403_07_박상준

---

flutter/01_start.md

240403_34_한정은

---

03.Flutter/001 개요.md
03.Flutter/002 Layout.md

240403_01_김동혁 TIL

---

flutter/how/lottie 활용.md

- install, 사용방법 정리
- (몰랐는데 22일차가 merge가 안되어 4/2일자로 들어가게되었습니당 ㅠ-ㅠ....)
- 추후 내용 추가하겠습니다!

240403_19_유지영 TIL

---

flutter/02_layout01.md

240403_17_신예진

---

flutter/[flutter] layout Widget_Column.md

 240404_10_변희선 

---

OrmCamp/5주차/4_일차.md

240404_35_황태욱

---

flutter/widget/BottomNavigationBar&Item.md
flutter/widget/silver appbar.md

youtube clone을 만들며 사용한 것 중
- silver appbar
- bottom navigation bar
개념 쪼금... 정리

240404_19_유지영 TIL

---

flutter/03. StatefulWidget의 생명주기.md

- StatefulWidget의 라이프사이클 알아보기
- 생성->초기화->빌드->소멸

240405_03_김세진

---

lecture/25일(Navigation).md

240405_15_송진섭

---

flutter/how/flutter_builder.md
flutter/life cycle.md

240405_19_유지영 TIL

---

flutter/04. MVVM 패턴.md

- MVVM 패턴이란?
- MVVM 패턴의 장점
- MVVM 패턴의 폴더 구조
- MVVM 패턴 작성 가이드

240408_03_김세진

---

Coding/MVVM.md
OrmCamp/6주차/1_일차.md

240408_35_황태욱

---

flutter/05_MVVM pattern.md

240409_17_신예진

---

flutter/04_MVVM.md

240408_34_한정은

---

flutter/mvvm와 notifier.md

240408_19_유지영 TIL

---

flutter/inheritedWidget.md

240409_19_유지영 TIL

---

flutter/05. InheritedWidget.md

240409_03_김세진

---

lecture/28일차 정리 (상태관리 라이브러리, ChangeNotifierProvider).md

Create 28일차 정리 (상태관리 라이브러리, ChangeNotifierProvider).md

240411_15_송진섭

---

flutter/05_ InheritedWidget.md

240409_34_한정은

---

flutter/06. 상태관리 라이브러리.md

- 상태관리 라이브러리
- Provider, Riverpod
- Provider을 이용한 실제 앱만드는 순서 정리

240411_03_김세진

---

Flutter/Provider.md
OrmCamp/6주차/4_일차.md

240411_35_황태욱

---

flutter/상태관리.md

240411_19_유지영 TIL

---

flutter/07. 상태 홀더 클래스.md

- 상태 홀더 클래스(State Holder Class) 정리

240412_03_김세진

---

Flutter/ViewModel 개선.md
OrmCamp/6주차/5_일차.md

240412_35_황태욱

---

flutter/07_UI.md

240412_34_한정은

---

lecture/30일차(go router와 provider 사용).md

Create 30일차(go router와 provider 사용).md

240415_15_송진섭

---

[git] branch.md
flutter/[flutter]provider.md

240415_10_변희선

---

Flutter/Shimmer.md
OrmCamp/7wnck/1_일차.md

240415_35_황태욱

---

03.Flutter/003 FutureBuilder.md
03.Flutter/004 Navigation.md

- FutureBuilder, Navigation 학습

240404_01_김동혁 TIL

---

git/05_branch&switch.md

240415_17_신예진

---

lecture/31일차(디바운스).md

240416_15_송진섭

---

[git] branch.md

240416_10_변희선

---

flutter/08. 클린아키텍쳐.md

- 클린 아키텍처(Clean Architecture)의 개념과 방법
- Use Case의 이해

240417_03_김세진

---

lecture/32일차 정리(Use Case,Clean Architecture)
lecture/32일차 정리(Use Case,Clean Architecture).md

Create 32일차 정리(Use Case,Clean Architecture)

240417_15_송진섭

---

lecture/33일차정리(깃관련 협업및 충돌관련 정리).md

Create 33일차정리(깃관련 협업및 충돌관련 정리).md

240418_15_송진섭

---

[git] git issues+branch.md

240418_10_변희선

---

lecture/34일차(다트 기타 문법사항 정리).md

240419_15_송진섭

---

[Git] issues 합치기
[git] branch.md
flutter/[flutter]이미지파일 안보일때.md

240419_10_변희선

---

flutter/09. Get It.md

240422_03_김세진

---

flutter/10. Stream.md

240423_03_김세진
